import type { EducationLevel, CardContentType } from '../../db/firestoreSchema';
function envStr(name: string): string | undefined { const v = process.env[name]; return v && v.trim() !== '' ? v : undefined; }
function envInt(name: string, fallback: number): number { const v = envStr(name); if (v === undefined) return fallback; const n = Number(v); return Number.isFinite(n) ? n : fallback; }
export interface CardTargets { minimumCards: number; targetCards: number; maximumCards: number; }
export interface ManagedSubject { subject: string; levels: EducationLevel[]; }
function loadManagedSubjects(): ManagedSubject[] { const raw = envStr('CONTENT_AGENT_SUBJECTS'); if (raw) { try { const parsed = JSON.parse(raw) as ManagedSubject[]; if (Array.isArray(parsed) && parsed.length > 0) return parsed; } catch (err) { console.warn('[agentConfig] CONTENT_AGENT_SUBJECTS inválido, usando lista padrão:', err); } } return [{ subject: 'Português', levels: ['fundamental', 'medio'] }, { subject: 'Matemática', levels: ['fundamental', 'medio'] }, { subject: 'Biologia', levels: ['medio', 'faculdade'] }, { subject: 'História do Brasil', levels: ['medio'] }, { subject: 'Direito Constitucional', levels: ['concurso', 'faculdade'] }, { subject: 'Direito Administrativo', levels: ['concurso', 'faculdade'] }, { subject: 'Raciocínio Lógico', levels: ['concurso'] }, { subject: 'Inglês', levels: ['fundamental', 'medio'] }]; }
export const CARD_CONTENT_TYPES: CardContentType[] = ['definition', 'quiz', 'gap', 'comparison', 'applied', 'review'];
export const DEFAULT_CARD_TYPE_DISTRIBUTION: Record<CardContentType, number> = { definition: 30, quiz: 20, gap: 10, comparison: 15, applied: 20, review: 5 };
export const agentConfig = {
  version: envStr('CONTENT_AGENT_VERSION') || '1.4.0', promptVersion: envStr('CONTENT_AGENT_PROMPT_VERSION') || 'cards-v5', enabled: envStr('CONTENT_AGENT_ENABLED') !== 'false', timezone: envStr('CONTENT_AGENT_TIMEZONE') || 'America/Campo_Grande', schedule: envStr('CONTENT_AGENT_SCHEDULE') || '*/15 * * * *', managedSubjects: loadManagedSubjects(), defaultDifficulty: envStr('CONTENT_AGENT_DIFFICULTY') || 'medium', defaultLanguage: 'pt',
  cardTargets: { minimumCards: envInt('CONTENT_AGENT_MIN_CARDS', 20), targetCards: envInt('CONTENT_AGENT_TARGET_CARDS', 60), maximumCards: envInt('CONTENT_AGENT_MAX_CARDS', 150) } satisfies CardTargets,
  activeCardTypes: (envStr('CONTENT_AGENT_CARD_TYPES')?.split(',').map(s => s.trim()).filter(Boolean) as CardContentType[] | undefined) ?? (['definition', 'quiz'] as CardContentType[]),
  limits: { maxRuntimeMinutes: envInt('CONTENT_AGENT_MAX_RUNTIME_MIN', 25), maxCardsPerRun: envInt('CONTENT_AGENT_MAX_CARDS_PER_RUN', 500), maxAiCallsPerRun: envInt('CONTENT_AGENT_MAX_AI_CALLS', 50), maxTopicsPerRun: envInt('CONTENT_AGENT_MAX_TOPICS', 20), maxRetries: envInt('CONTENT_AGENT_MAX_RETRIES', 2), requestProcessingTimeoutMinutes: envInt('CONTENT_AGENT_REQUEST_TIMEOUT_MIN', 120), batchSize: envInt('CONTENT_AGENT_BATCH_SIZE', 20), maxCardsReviewedPerTopic: envInt('CONTENT_AGENT_MAX_CARDS_REVIEWED', 5), maxContentRequestsPerRun: envInt('CONTENT_AGENT_MAX_REQUESTS', 2), maxRequestTopicsPerRun: envInt('CONTENT_AGENT_MAX_REQUEST_TOPICS', 12) },
  quality: { minimumScore: Number(envStr('CONTENT_AGENT_QUALITY_MIN') || '0.72'), minimumGrounding: Number(envStr('CONTENT_AGENT_GROUNDING_MIN') || '0.18') },
  feedbackThresholds: { minFeedbackCount: envInt('CONTENT_AGENT_MIN_FEEDBACK', 20), minNegativeCount: envInt('CONTENT_AGENT_MIN_NEGATIVE', 5), minNegativeRate: envInt('CONTENT_AGENT_MIN_NEGATIVE_RATE', 0.3) },
  cardReviewThresholds: { minFeedbackCount: envInt('CONTENT_AGENT_CARD_MIN_FEEDBACK', 5), minNegativeRate: envInt('CONTENT_AGENT_CARD_MIN_NEGATIVE_RATE', 0.5) },
};
export type AgentConfig = typeof agentConfig;
