import { getAdminFirestore } from '../firebaseAdmin';
import { SubjectDoc, CurriculumDoc, CardBucketDoc, BankCard, EducationLevel, CardContentType, ContentIndexDoc, ContentRequestDoc, AgentMetricDoc, subjectId, curriculumId, bucketId, contentIndexId, normalizeText, slugify, contentHash, shortHash, makeTtl, isExpired, TTL_DAYS } from './firestoreSchema';
export type { BankCard, EducationLevel, CardContentType, SubjectDoc, CurriculumDoc, CardBucketDoc, ContentIndexDoc, ContentRequestDoc, AgentMetricDoc };

export async function getSubjectLevels(subject: string): Promise<{ data: SubjectDoc; fromCache: true } | null> { const db=getAdminFirestore();if(!db)return null;try{const s=await db.collection('subjects').doc(subjectId(subject)).get();if(!s.exists)return null;const d=s.data() as SubjectDoc;return isExpired(d.ttlAt)?null:{data:d,fromCache:true};}catch{return null;} }
export async function saveSubjectLevels(subject:string,levels:SubjectDoc['levels'],providerUsed:string):Promise<void>{const db=getAdminFirestore();if(!db)return;const old=await db.collection('subjects').doc(subjectId(subject)).get();const prev=(old.data() as SubjectDoc|undefined);const doc:SubjectDoc={subject:subject.trim(),normalized:normalizeText(subject),levels,updatedAt:new Date().toISOString(),ttlAt:makeTtl(TTL_DAYS.SUBJECT_LEVELS),providerUsed,version:(prev?.version??0)+1,totalCurricula:prev?.totalCurricula??0,totalTopics:prev?.totalTopics??0,totalSubtopics:prev?.totalSubtopics??0,totalCards:prev?.totalCards??0};await db.collection('subjects').doc(subjectId(subject)).set(doc);await upsertContentIndex(subject,prev?.version??0);}
export async function getCurriculum(subject:string,level:EducationLevel):Promise<{data:CurriculumDoc;fromCache:true}|null>{const db=getAdminFirestore();if(!db)return null;try{const s=await db.collection('curricula').doc(curriculumId(subject,level)).get();if(!s.exists)return null;const d=s.data() as CurriculumDoc;return isExpired(d.ttlAt)?null:{data:d,fromCache:true};}catch{return null;}}
export async function saveCurriculum(subject:string,level:EducationLevel,categories:CurriculumDoc['categories'],providerUsed:string,topicTree:CurriculumDoc['topicTree']=undefined):Promise<void>{const db=getAdminFirestore();if(!db)return;const totalTopics=topicTree?.length??categories.reduce((n,c)=>n+c.topics.length,0);const totalSubtopics=topicTree?.reduce((n,t)=>n+t.subtopics.length,0)??0;const ref=db.collection('curricula').doc(curriculumId(subject,level));const old=await ref.get();const prev=(old.data() as CurriculumDoc|undefined);const doc:CurriculumDoc={subject:subject.trim(),level,categories,topicTree,topicCount:totalTopics,subtopicCount:totalSubtopics,totalTopics,totalSubtopics,totalCards:prev?.totalCards??0,version:(prev?.version??0)+1,contentVersion:new Date().toISOString().slice(0,7),updatedAt:new Date().toISOString(),ttlAt:makeTtl(TTL_DAYS.CURRICULUM),providerUsed};await ref.set(doc);await updateContentTotals(subject);}

export async function getCardBucket(subject:string,topic:string,level:EducationLevel,cardType:CardContentType,limit:number,subtopic=''):Promise<{cards:BankCard[];stale:boolean}>{const db=getAdminFirestore();if(!db||limit<=0)return{cards:[],stale:true};try{const s=await db.collection('cardBuckets').doc(bucketId(subject,topic,level,cardType,subtopic)).get();if(!s.exists)return{cards:[],stale:true};const d=s.data() as CardBucketDoc;const cards=Array.isArray(d.cards)?d.cards.slice():[];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}return{cards:cards.slice(0,limit),stale:isExpired(d.ttlAt)};}catch{return{cards:[],stale:true};}}
export async function saveCardBucket(subject:string,topic:string,level:EducationLevel,cardType:CardContentType,newCards:Omit<BankCard,'id'>[],providerUsed:string,subtopic=''):Promise<void>{const db=getAdminFirestore();if(!db||!newCards.length)return;const ref=db.collection('cardBuckets').doc(bucketId(subject,topic,level,cardType,subtopic));const snap=await ref.get();const existing=new Map<string,BankCard>();if(snap.exists){const d=snap.data() as CardBucketDoc;(d.cards||[]).forEach(c=>existing.set(c.contentHash??contentHash(c.front,c.back,`${subject}|${topic}|${subtopic}`),c));}let added=0,duplicates=0;for(const card of newCards){if(!card.front)continue;const h=contentHash(card.front,card.back,`${subject}|${topic}|${subtopic}`);if(existing.has(h)){duplicates++;continue;}const id=shortHash(h);existing.set(h,{...card,id,contentHash:h,version:1,subtopic});added++;}if(!added&&!snap.exists)return;const all=Array.from(existing.values());await ref.set({subject:subject.trim(),topic:topic.trim(),subtopic:subtopic||undefined,level,cardType,cards:all,cardCount:all.length,version:((snap.data() as CardBucketDoc|undefined)?.version??0)+1,updatedAt:new Date().toISOString(),ttlAt:makeTtl(TTL_DAYS.CARD_BUCKET),providerUsed},{merge:true});if(duplicates)await incrementAgentMetric({duplicates});await updateContentTotals(subject);}
export async function getBucketStats(subject:string,topics:string[],level:EducationLevel,cardType:CardContentType='definition'){const db=getAdminFirestore();if(!db)return[];return Promise.all(topics.map(async topic=>{const id=bucketId(subject,topic,level,cardType);try{const s=await db.collection('cardBuckets').doc(id).get();if(!s.exists)return{topic,cardCount:0,stale:true,bucketId:id};const d=s.data() as CardBucketDoc;return{topic,cardCount:d.cardCount??d.cards?.length??0,stale:isExpired(d.ttlAt),bucketId:id};}catch{return{topic,cardCount:0,stale:true,bucketId:id};}}));}
export async function prefetchCardBuckets(subject:string,topics:string[],level:EducationLevel,cardType:CardContentType){const db=getAdminFirestore();const out=new Map<string,{cards:BankCard[];stale:boolean}>();if(!db)return out;await Promise.all(topics.map(async t=>{const id=bucketId(subject,t,level,cardType);try{const s=await db.collection('cardBuckets').doc(id).get();out.set(id,s.exists?{cards:(s.data() as CardBucketDoc).cards??[],stale:isExpired((s.data() as CardBucketDoc).ttlAt)}:{cards:[],stale:true});}catch{out.set(id,{cards:[],stale:true});}}));return out;}

export async function upsertContentIndex(subject:string,version=1):Promise<void>{const db=getAdminFirestore();if(!db)return;const id=contentIndexId(subject);const ref=db.collection('contentIndex').doc(id);const old=await ref.get();const d=(old.data() as ContentIndexDoc|undefined);await ref.set({subjectId:subjectId(subject),subject:subject.trim(),normalized:normalizeText(subject),aliases:Array.from(new Set([...(d?.aliases??[]),normalizeText(subject),slugify(subject)])),status:d?.status??'ready',version:Math.max(version,d?.version??1),totalTopics:d?.totalTopics??0,totalSubtopics:d?.totalSubtopics??0,totalCards:d?.totalCards??0,updatedAt:new Date().toISOString()},{merge:true});}
export async function getContentIndex(subject:string):Promise<ContentIndexDoc|null>{const db=getAdminFirestore();if(!db)return null;const s=await db.collection('contentIndex').doc(contentIndexId(subject)).get();return s.exists?(s.data() as ContentIndexDoc):null;}
export async function enqueueContentRequest(requestedSubject:string,educationLevel?:EducationLevel,priority=5):Promise<string|null>{const db=getAdminFirestore();if(!db)return null;const subject=requestedSubject.trim();if(!subject)return null;const normalized=normalizeText(subject);const ref=db.collection('contentRequests').doc(contentIndexId(subject));const now=new Date().toISOString();const old=await ref.get();if(old.exists){const previous=old.data() as ContentRequestDoc;await ref.set({subject,requestedSubject:subject,normalizedSubject:normalized,requestCount:(previous.requestCount??0)+1,priority:Math.max(priority,previous.priority??0),status:'pending',requestedAt:previous.requestedAt??now,updatedAt:now},{merge:true});return ref.id;}const doc:ContentRequestDoc={subject,requestedSubject:subject,normalizedSubject:normalized,subjectId:subjectId(subject),educationLevel,status:'pending',priority,requestCount:1,attempts:0,createdAt:now,requestedAt:now,updatedAt:now};await ref.set(doc);return ref.id;}
export async function updateContentTotals(subject:string):Promise<void>{const db=getAdminFirestore();if(!db)return;const idx=await db.collection('contentIndex').doc(contentIndexId(subject)).get();if(!idx.exists)return;await idx.ref.set({updatedAt:new Date().toISOString()},{merge:true});}
export async function incrementAgentMetric(delta:Partial<AgentMetricDoc>):Promise<void>{const db=getAdminFirestore();if(!db)return;const id=new Date().toISOString().slice(0,10);const ref=db.collection('agentMetrics').doc(id);const old=await ref.get();const d=(old.data() as Partial<AgentMetricDoc>|undefined)||{};const next:any={date:id,updatedAt:new Date().toISOString()};for(const k of ['runs','aiCalls','geminiCalls','deepseekCalls','openaiCalls','cardsGenerated','tokensInput','tokensOutput','cacheHits','cacheMisses','estimatedAiCostUsd','duplicates','errors'])next[k]=Number(d[k]??0)+Number((delta as any)[k]??0);await ref.set(next,{merge:true});}
