import { getAdminFirestore } from '../../firebaseAdmin';
import { bucketId } from '../../db/firestoreSchema';
import type { CardBucketDoc, EducationLevel, CardContentType, BankCard } from '../../db/firestoreSchema';

export async function loadBucket(subject:string,topic:string,level:EducationLevel,cardType:CardContentType):Promise<CardBucketDoc|null>{const db=getAdminFirestore();if(!db)return null;const id=bucketId(subject,topic,level,cardType);const snap=await db.collection('cardBuckets').doc(id).get();return snap.exists?(snap.data() as CardBucketDoc):null;}
export interface CardRevisionHistoryEntry{bucketId:string;subject:string;topic:string;level:EducationLevel;cardType:CardContentType;reviewVersion:number;removedCards:BankCard[];qualityScore:number;removedAt:string;restoredAt?:string;}
export async function removeCardsFromBucket(subject:string,topic:string,level:EducationLevel,cardType:CardContentType,cardIdsToRemove:string[],qualityScore:number):Promise<{removed:number}|null>{const db=getAdminFirestore();if(!db||!cardIdsToRemove.length)return null;const id=bucketId(subject,topic,level,cardType);const ref=db.collection('cardBuckets').doc(id);const snap=await ref.get();if(!snap.exists)return null;const doc=snap.data() as CardBucketDoc;const toRemove=new Set(cardIdsToRemove);const removedCards=(doc.cards||[]).filter(c=>toRemove.has(c.id));const remaining=(doc.cards||[]).filter(c=>!toRemove.has(c.id));const removed=removedCards.length;if(!removed)return{removed:0};const nextVersion=(doc.reviewVersion??0)+1;const now=new Date().toISOString();const updated:CardBucketDoc={...doc,cards:remaining,cardCount:remaining.length,qualityScore,reviewVersion:nextVersion,lastReviewedAt:now,updatedAt:now};const historyEntry:CardRevisionHistoryEntry={bucketId:id,subject,topic,level,cardType,reviewVersion:nextVersion,removedCards,qualityScore,removedAt:now};await db.collection('cardRevisionHistory').doc(`${id}_v${nextVersion}`).set(historyEntry);await ref.set(updated);return{removed};}
export async function replaceCardInBucket(subject:string,topic:string,level:EducationLevel,cardType:CardContentType,oldCardId:string,replacement:Omit<BankCard,'id'>,reason:string):Promise<boolean>{const db=getAdminFirestore();if(!db)return false;const id=bucketId(subject,topic,level,cardType);const ref=db.collection('cardBuckets').doc(id);const snap=await ref.get();if(!snap.exists)return false;const doc=snap.data() as CardBucketDoc;const index=(doc.cards||[]).findIndex(c=>c.id===oldCardId);if(index<0)return false;const oldCard=doc.cards[index];const newCard:BankCard={...replacement,id:oldCardId,version:(oldCard.version??1)+1,contentHash:replacement.contentHash||oldCard.contentHash};const cards=[...(doc.cards||[])];cards[index]=newCard;const now=new Date().toISOString();const reviewVersion=(doc.reviewVersion??0)+1;await db.collection('cardCorrectionHistory').doc(`${id}_v${reviewVersion}_${oldCardId}`).set({bucketId:id,subject,topic,level,cardType,oldCard,newCard,reason,correctedAt:now,reviewVersion});await ref.set({...doc,cards,cardCount:cards.length,version:(doc.version??1)+1,reviewVersion,lastReviewedAt:now,updatedAt:now});return true;}
export async function rollbackLastReview(subject:string,topic:string,level:EducationLevel,cardType:CardContentType):Promise<{restored:number;reviewVersion:number}|null>{const db=getAdminFirestore();if(!db)return null;const id=bucketId(subject,topic,level,cardType);const snap=await db.collection('cardRevisionHistory').where('bucketId','==',id).orderBy('reviewVersion','desc').limit(1).get();if(snap.empty)return null;const entryDoc=snap.docs[0];const entry=entryDoc.data() as CardRevisionHistoryEntry;if(entry.restoredAt)return{restored:0,reviewVersion:entry.reviewVersion};const bucketRef=db.collection('cardBuckets').doc(id);const bucketSnap=await bucketRef.get();if(!bucketSnap.exists)return null;const doc=bucketSnap.data() as CardBucketDoc;const existingIds=new Set((doc.cards||[]).map(c=>c.id));const toRestore=entry.removedCards.filter(c=>!existingIds.has(c.id));const restoredCards=[...(doc.cards||[]),...toRestore];await bucketRef.set({...doc,cards:restoredCards,cardCount:restoredCards.length,updatedAt:new Date().toISOString()});await entryDoc.ref.set({...entry,restoredAt:new Date().toISOString()});return{restored:toRestore.length,reviewVersion:entry.reviewVersion};}
